CITY_CHOICE  = (
	("Mumbai", "Mumbai" ),
	("Delhi", "Delhi"),
	("Bengaluru", "Bengaluru"),
	("Ahmedabad", "Ahmedabad"),
	("Hyderabad", "Hyderabad"),
	("Chennai", "Chennai"),
	("Kolkata", "Kolkata"),
	("Pune", "Pune"),
	("Jaipur", "Jaipur"),
	("Surat", "Surat"),
	("Lucknow", "Lucknow"),
	("Kanpur", "Kanpur"),
	("Nagpur", "Nagpur"),
	("Patna", "Patna"),
	("Indore", "Indore"),
	("Thane", "Thane"),
	("Bhopal", "Bhopal"),
	("Visakhapatnam", "Visakhapatnam"),
	("Vadodara", "Vadodara"),
	("Firozabad", "Firozabad"),
	("Ludhiana", "Ludhiana"),
	("Rajkot", "Rajkot"),
	("Agra", "Agra"),
	("Siliguri", "Siliguri"),
	("Nashik", "Nashik"),
	("Faridabad", "Faridabad"),
	("Patiala", "Patiala"),
	("Meerut", "Meerut"),
	("Kalyan-Dombivali", "Kalyan-Dombivali"),
	("Vasai-Virar", "Vasai-Virar"),
	("Varanasi", "Varanasi"),
	("Srinagar", "Srinagar"),
	("Dhanbad", "Dhanbad"),
	("Jodhpur", "Jodhpur"),
	("Amritsar", "Amritsar"),
	("Raipur", "Raipur"),
	("Allahabad", "Allahabad"),
	("Coimbatore", "Coimbatore"),
	("Jabalpur", "Jabalpur"),
	("Gwalior", "Gwalior"),
	("Vijayawada", "Vijayawada"),
	("Madurai", "Madurai"),
	("Guwahati", "Guwahati"),
	("Chandigarh", "Chandigarh"),
	("Hubli-Dharwad", "Hubli-Dharwad"),
	("Amroha", "Amroha"),
	("Moradabad", "Moradabad"),
	("Gurgaon", "Gurgaon"),
	("Aligarh", "Aligarh"),
	("Solapur", "Solapur"),
	("Ranchi", "Ranchi"),
	("Jalandhar", "Jalandhar"),
	("Tiruchirappalli", "Tiruchirappalli"),
	("Bhubaneswar", "Bhubaneswar"),
	("Salem", "Salem"),
	("Warangal", "Warangal"),
	("Mira-Bhayandar", "Mira-Bhayandar"),
	("Thiruvananthapuram", "Thiruvananthapuram"),
	("Bhiwandi", "Bhiwandi"),
	("Saharanpur", "Saharanpur"),
	)


STATE_CHOICE  = (
	("Maharashtra", "Maharashtra" ),
	("Delhi", "Delhi"),
	("Karnataka", "Karnataka"),
	("Gujarat", "Gujarat"),
	("Telangana", "Telangana"),
	("Tamil Nadu", "Tamil Nadu"),
	("West Bengal", "West Bengal"),
	("Rajasthan", "Rajasthan"),
	("Uttar Pradesh", "Uttar Pradesh"),
	("Bihar", "Bihar"),
	("Madhya Pradesh", "Madhya Pradesh"),
	("Andhra Pradesh", "Andhra Pradesh"),
	("Punjab", "Punjab"),
	("Haryana", "Haryana"),
	("Jammu and Kashmir", "Jammu and Kashmir"),
	("Jharkhand", "Jharkhand"),
	("Chhattisgarh", "Chhattisgarh"),
	("Assam", "Assam"),
	("Chandigarh", "Chandigarh"),
	("Odisha", "Odisha"),
	("Kerala", "Kerala"),
	("Uttarakhand", "Uttarakhand"),
	("Puducherry", "Puducherry"),
	("Tripura", "Tripura"),
	("Mizoram", "Mizoram"),
	("Meghalaya", "Meghalaya"),
	("Manipur", "Manipur"),
	("Himachal Pradesh", "Himachal Pradesh"),
	)

COUNTRY_CHOICE  = (
	("Afghanistan", "Afghanistan" ),
	("Albania", "Albania"),
	("Algeria", "Algeria"),
	("Andorra", "Andorra"),
	("Angola", "Angola"),
	("Antigua and Barbuda", "Antigua and Barbuda"),
	("Argentina", "Argentina"),
	("Armenia", "Armenia"),
	("Australia", "Australia"),
	("Austria", "Austria"),
	("Azerbaijan", "Azerbaijan"),
	("Bahamas", "Bahamas"),
	("Bahrain", "Bahrain"),
	("Bangladesh", "Bangladesh"),
	("Barbados", "Barbados"),
	("Belarus", "Belarus"),
	("Belgium", "Belgium"),
	("Belize", "Belize"),
	("Benin", "Benin"),
	("Bhutan", "Bhutan"),
	("Bolivia", "Bolivia"),
	("Bosnia and Herzegovina", "Bosnia and Herzegovina"),
	("Botswana", "Botswana"),
	("Brazil", "Brazil"),
	("Brunei Darussalam", "Brunei Darussalam"),
	("Bulgaria", "Bulgaria"),
	("Burkina Faso", "Burkina Faso"),
	("Burundi", "Burundi"),
	)