# Generated by Django 2.0.7 on 2018-08-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_reg', models.DateField(blank=True, null=True)),
                ('salutation', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('country_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('ocp_history', models.CharField(blank=True, max_length=255, null=True)),
                ('income', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('pa_address_detail', models.TextField(blank=True, max_length=255, null=True)),
                ('pa_city', models.CharField(blank=True, max_length=255, null=True)),
                ('pa_state', models.CharField(blank=True, max_length=255, null=True)),
                ('pa_country', models.CharField(blank=True, max_length=255, null=True)),
                ('ta_address_detail', models.TextField(blank=True, max_length=255, null=True)),
                ('ta_city', models.CharField(blank=True, max_length=255, null=True)),
                ('ta_state', models.CharField(blank=True, max_length=255, null=True)),
                ('ta_country', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('rf_salutation', models.CharField(blank=True, max_length=255, null=True)),
                ('rf_name', models.CharField(blank=True, max_length=255, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Patient Data',
            },
        ),
    ]
