# Generated by Django 2.0.7 on 2018-08-17 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True, max_length=255, null=True)),
                ('tablet', models.CharField(blank=True, max_length=255, null=True)),
                ('mrg_count', models.CharField(blank=True, max_length=255, null=True)),
                ('aft_count', models.CharField(blank=True, max_length=255, null=True)),
                ('nit_count', models.CharField(blank=True, max_length=255, null=True)),
                ('tab_qty', models.CharField(blank=True, max_length=255, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.PatientData', verbose_name='Patient')),
            ],
            options={
                'verbose_name_plural': 'Prescription',
            },
        ),
    ]
