# Generated by Django 2.0.7 on 2018-08-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20180809_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
