# Generated by Django 2.0.7 on 2018-08-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20180810_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='education',
            field=models.CharField(blank=True, choices=[('Illiterate', 'Illiterate'), ('Schooling', 'Schooling'), ('UG', 'UG'), ('PG', 'PG')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='income',
            field=models.CharField(blank=True, choices=[('Lower(<10,000/m)', 'Lower(<10,000/m)'), ('Middle(10,000-30,000/m)', 'Middle(10,000-30,000/m)'), ('Higher(>30,000/m)', 'Higher(>30,000/m)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='occupation',
            field=models.CharField(blank=True, choices=[('Self', 'Self'), ('Salaried', 'Salaried'), ('Student', 'Student'), ('Professional', 'Professional'), ('House wife', 'House wife'), ('Retired', 'Retired'), ('Unemployed', 'Unemployed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='pa_city',
            field=models.CharField(blank=True, choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Bengaluru', 'Bengaluru'), ('Ahmedabad', 'Ahmedabad'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('Pune', 'Pune'), ('Jaipur', 'Jaipur'), ('Surat', 'Surat'), ('Lucknow', 'Lucknow'), ('Kanpur', 'Kanpur'), ('Nagpur', 'Nagpur'), ('Patna', 'Patna'), ('Indore', 'Indore'), ('Thane', 'Thane'), ('Bhopal', 'Bhopal'), ('Visakhapatnam', 'Visakhapatnam'), ('Vadodara', 'Vadodara'), ('Firozabad', 'Firozabad'), ('Ludhiana', 'Ludhiana'), ('Rajkot', 'Rajkot'), ('Agra', 'Agra'), ('Siliguri', 'Siliguri'), ('Nashik', 'Nashik'), ('Faridabad', 'Faridabad'), ('Patiala', 'Patiala'), ('Meerut', 'Meerut'), ('Kalyan-Dombivali', 'Kalyan-Dombivali'), ('Vasai-Virar', 'Vasai-Virar'), ('Varanasi', 'Varanasi'), ('Srinagar', 'Srinagar'), ('Dhanbad', 'Dhanbad'), ('Jodhpur', 'Jodhpur'), ('Amritsar', 'Amritsar'), ('Raipur', 'Raipur'), ('Allahabad', 'Allahabad'), ('Coimbatore', 'Coimbatore'), ('Jabalpur', 'Jabalpur'), ('Gwalior', 'Gwalior'), ('Vijayawada', 'Vijayawada'), ('Madurai', 'Madurai'), ('Guwahati', 'Guwahati'), ('Chandigarh', 'Chandigarh'), ('Hubli-Dharwad', 'Hubli-Dharwad'), ('Amroha', 'Amroha'), ('Moradabad', 'Moradabad'), ('Gurgaon', 'Gurgaon'), ('Aligarh', 'Aligarh'), ('Solapur', 'Solapur'), ('Ranchi', 'Ranchi'), ('Jalandhar', 'Jalandhar'), ('Tiruchirappalli', 'Tiruchirappalli'), ('Bhubaneswar', 'Bhubaneswar'), ('Salem', 'Salem'), ('Warangal', 'Warangal'), ('Mira-Bhayandar', 'Mira-Bhayandar'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Bhiwandi', 'Bhiwandi'), ('Saharanpur', 'Saharanpur')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='pa_country',
            field=models.CharField(blank=True, choices=[('Afghanistan', 'Afghanistan'), ('Albania', 'Albania'), ('Algeria', 'Algeria'), ('Andorra', 'Andorra'), ('Angola', 'Angola'), ('Antigua and Barbuda', 'Antigua and Barbuda'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Azerbaijan', 'Azerbaijan'), ('Bahamas', 'Bahamas'), ('Bahrain', 'Bahrain'), ('Bangladesh', 'Bangladesh'), ('Barbados', 'Barbados'), ('Belarus', 'Belarus'), ('Belgium', 'Belgium'), ('Belize', 'Belize'), ('Benin', 'Benin'), ('Bhutan', 'Bhutan'), ('Bolivia', 'Bolivia'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('Botswana', 'Botswana'), ('Brazil', 'Brazil'), ('Brunei Darussalam', 'Brunei Darussalam'), ('Bulgaria', 'Bulgaria'), ('Burkina Faso', 'Burkina Faso'), ('Burundi', 'Burundi')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='pa_state',
            field=models.CharField(blank=True, choices=[('Maharashtra', 'Maharashtra'), ('Delhi', 'Delhi'), ('Karnataka', 'Karnataka'), ('Gujarat', 'Gujarat'), ('Telangana', 'Telangana'), ('Tamil Nadu', 'Tamil Nadu'), ('West Bengal', 'West Bengal'), ('Rajasthan', 'Rajasthan'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Bihar', 'Bihar'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Punjab', 'Punjab'), ('Haryana', 'Haryana'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Chhattisgarh', 'Chhattisgarh'), ('Assam', 'Assam'), ('Chandigarh', 'Chandigarh'), ('Odisha', 'Odisha'), ('Kerala', 'Kerala'), ('Uttarakhand', 'Uttarakhand'), ('Puducherry', 'Puducherry'), ('Tripura', 'Tripura'), ('Mizoram', 'Mizoram'), ('Meghalaya', 'Meghalaya'), ('Manipur', 'Manipur'), ('Himachal Pradesh', 'Himachal Pradesh')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='rf_salutation',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Baby', 'Baby'), ('Master', 'Master'), ('Sister', 'Sister'), ('Brother', 'Brother'), ('Father', 'Father')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Baby', 'Baby'), ('Master', 'Master'), ('Sister', 'Sister'), ('Brother', 'Brother'), ('Father', 'Father')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='ta_city',
            field=models.CharField(blank=True, choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Bengaluru', 'Bengaluru'), ('Ahmedabad', 'Ahmedabad'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('Pune', 'Pune'), ('Jaipur', 'Jaipur'), ('Surat', 'Surat'), ('Lucknow', 'Lucknow'), ('Kanpur', 'Kanpur'), ('Nagpur', 'Nagpur'), ('Patna', 'Patna'), ('Indore', 'Indore'), ('Thane', 'Thane'), ('Bhopal', 'Bhopal'), ('Visakhapatnam', 'Visakhapatnam'), ('Vadodara', 'Vadodara'), ('Firozabad', 'Firozabad'), ('Ludhiana', 'Ludhiana'), ('Rajkot', 'Rajkot'), ('Agra', 'Agra'), ('Siliguri', 'Siliguri'), ('Nashik', 'Nashik'), ('Faridabad', 'Faridabad'), ('Patiala', 'Patiala'), ('Meerut', 'Meerut'), ('Kalyan-Dombivali', 'Kalyan-Dombivali'), ('Vasai-Virar', 'Vasai-Virar'), ('Varanasi', 'Varanasi'), ('Srinagar', 'Srinagar'), ('Dhanbad', 'Dhanbad'), ('Jodhpur', 'Jodhpur'), ('Amritsar', 'Amritsar'), ('Raipur', 'Raipur'), ('Allahabad', 'Allahabad'), ('Coimbatore', 'Coimbatore'), ('Jabalpur', 'Jabalpur'), ('Gwalior', 'Gwalior'), ('Vijayawada', 'Vijayawada'), ('Madurai', 'Madurai'), ('Guwahati', 'Guwahati'), ('Chandigarh', 'Chandigarh'), ('Hubli-Dharwad', 'Hubli-Dharwad'), ('Amroha', 'Amroha'), ('Moradabad', 'Moradabad'), ('Gurgaon', 'Gurgaon'), ('Aligarh', 'Aligarh'), ('Solapur', 'Solapur'), ('Ranchi', 'Ranchi'), ('Jalandhar', 'Jalandhar'), ('Tiruchirappalli', 'Tiruchirappalli'), ('Bhubaneswar', 'Bhubaneswar'), ('Salem', 'Salem'), ('Warangal', 'Warangal'), ('Mira-Bhayandar', 'Mira-Bhayandar'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Bhiwandi', 'Bhiwandi'), ('Saharanpur', 'Saharanpur')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='ta_country',
            field=models.CharField(blank=True, choices=[('Afghanistan', 'Afghanistan'), ('Albania', 'Albania'), ('Algeria', 'Algeria'), ('Andorra', 'Andorra'), ('Angola', 'Angola'), ('Antigua and Barbuda', 'Antigua and Barbuda'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Azerbaijan', 'Azerbaijan'), ('Bahamas', 'Bahamas'), ('Bahrain', 'Bahrain'), ('Bangladesh', 'Bangladesh'), ('Barbados', 'Barbados'), ('Belarus', 'Belarus'), ('Belgium', 'Belgium'), ('Belize', 'Belize'), ('Benin', 'Benin'), ('Bhutan', 'Bhutan'), ('Bolivia', 'Bolivia'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('Botswana', 'Botswana'), ('Brazil', 'Brazil'), ('Brunei Darussalam', 'Brunei Darussalam'), ('Bulgaria', 'Bulgaria'), ('Burkina Faso', 'Burkina Faso'), ('Burundi', 'Burundi')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='ta_state',
            field=models.CharField(blank=True, choices=[('Maharashtra', 'Maharashtra'), ('Delhi', 'Delhi'), ('Karnataka', 'Karnataka'), ('Gujarat', 'Gujarat'), ('Telangana', 'Telangana'), ('Tamil Nadu', 'Tamil Nadu'), ('West Bengal', 'West Bengal'), ('Rajasthan', 'Rajasthan'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Bihar', 'Bihar'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Punjab', 'Punjab'), ('Haryana', 'Haryana'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Chhattisgarh', 'Chhattisgarh'), ('Assam', 'Assam'), ('Chandigarh', 'Chandigarh'), ('Odisha', 'Odisha'), ('Kerala', 'Kerala'), ('Uttarakhand', 'Uttarakhand'), ('Puducherry', 'Puducherry'), ('Tripura', 'Tripura'), ('Mizoram', 'Mizoram'), ('Meghalaya', 'Meghalaya'), ('Manipur', 'Manipur'), ('Himachal Pradesh', 'Himachal Pradesh')], max_length=50, null=True),
        ),
    ]
