# Generated by Django 2.0.7 on 2018-08-15 13:14

import apps.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20180813_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_files', models.FileField(blank=True, null=True, upload_to=apps.models.file_upload)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.PatientData', verbose_name='Patient')),
            ],
            options={
                'verbose_name_plural': 'Patient Files',
            },
        ),
    ]
